USE DBRIESGOS
GO

	TRUNCATE TABLE DW_Raw_v2.dbo.CMGMora_Recaudo

	;WITH recaudo as(
		SELECT 
			CAST(FECHA_CIERRE as date) FECHA_CIERRE
			,CAST(SALDO as float) SALDO
			,CAST(RECAUDO as float) RECAUDO
			,CAST(TASA as float) TASA
			,CORREDOR ,GRUPO ,TERRITORIO
			,LTRIM(RTRIM(TERRITORIO))+'-'+LTRIM(RTRIM(GRUPO))+'-'+LTRIM(RTRIM(CORREDOR)) TER_GRU_COR
			,CASE WHEN CORREDOR IN ('SIN ASIGNAR', 'TOTAL') THEN 20
			ELSE 19 END TIP_COD
		FROM dbriesgos.dbo.RECAUDO_DIARIO_FINANZAS
	)
	INSERT INTO DW_Raw_v2.dbo.CMGMora_Recaudo
	SELECT
		B.FECHA_CIERRE AS SFECPRO
		,B.CORREDOR ,B.GRUPO ,B.TERRITORIO
		,B.TIP_COD AS STIPCOD
		,J.RCODCOR AS SCODREL
		,B.RECAUDO AS SMONREC
		,B.TASA AS STASREC
		,0 AS SRECCAST12M
		,0 AS SSTKPROV	
		,0 AS SGASPROVCART	
		,0 AS SGASPROVCONTA	
		,0 AS SGASPROVOM3155	
		,0 AS SGASPROVVOLU	
		,0 AS SGASPROVBRUTO	
		,0 AS SGASPROVBRUTO12M
	FROM recaudo B
	LEFT JOIN DW_Raw_v2.dbo.CMGMora_STRJERCOR J ON (B.TER_GRU_COR=J.[TER-GRU-COR])
	ORDER BY B.CORREDOR, B.TERRITORIO, B.GRUPO -- NO MOVER 


	UPDATE DW_Raw_v2.dbo.CMGMora_Recaudo SET STIPCOD = 7 WHERE CORREDOR IN ('TOTAL') AND GRUPO IN ('TOTAL')
	

	SELECT 
		DISTINCT SFECPRO as FECHA_CIERRE
	FROM DW_Raw_v2.dbo.CMGMora_Recaudo


