USE DBRIESGOS
GO


	--ACTUALIZAR CADA RECEPCION DEL ARCHIVO DE RIESGOS (KARLA) (MENSUAL)
	-- HOJA:  GASTO DE PROVISIONES - FC
		-- CAMPO: GASTO OM3155 = SGASPROVOM3155
		-- CAMPO: GASTO PROVISIONES BRUTO (SUMA DE LOS ULTIMOS 11 MESES) = SGASPROVBRUTO12M
		-- CAMPO: SRECCAST12M = CASTIGOS = VALOR DESDE P002-CASTIGOS.sql (MENSUAL)

		UPDATE DW_Raw_v2.dbo.CMGMora_Recaudo 
		SET 
			SRECCAST12M = 3437395.96
			,SGASPROVBRUTO12M = 69127536.6
			,SGASPROVOM3155 = 0
		WHERE STIPCOD = 7


DECLARE @FecRep date
SET @FecRep = ( SELECT DISTINCT SFECPRO FROM DW_Raw_v2.dbo.CMGMora_Recaudo )
DECLARE @SSTKPROV float = NULL;
DECLARE @SGASPROVCART float = NULL;
DECLARE @SGASPROVCONTA float = NULL;



DECLARE @NombreTabla VARCHAR(100);
DECLARE @SQL NVARCHAR(MAX); 
SET @NombreTabla = '[dbriesgos].[dbo].[PROV_PROY_' + CONVERT(VARCHAR(8), @FecRep, 112) + '_0]';
SET @SQL = N'

	DECLARE @SSTKPROV float = NULL;
	DECLARE @SGASPROVCART float = NULL;
	DECLARE @SGASPROVCONTA float = NULL;
	SET @SSTKPROV = (SELECT SUM(PROVISION_PROYECTADA) FROM ' + @NombreTabla+');' 
	+'SET @SGASPROVCART = (SELECT ISNULL(SUM(GASTO_OPE),0.00) FROM [dbriesgos].[dbo].GASTO_PROV_OPE_DIARIA WHERE FC_DIA = CONVERT(varchar,'''+ CAST(@FecRep AS VARCHAR(10)) +''',23)'+');'
	+'SET @SGASPROVCONTA = (SELECT ISNULL(SUM(GASTO_OPE),0.00) FROM [dbriesgos].[dbo].GASTO_PROV_OPE_DIARIA WHERE FC_DIA = CONVERT(varchar,'''+ CAST(@FecRep AS VARCHAR(10)) +''',23)'+');'
	+'
		SELECT ''SSTKPROV'' as VARIABLE, SUM(PROVISION_PROYECTADA) as VALOR FROM ' + @NombreTabla 
	+ '
		UNION
		SELECT ''SGASPROVCART'' as VARIABLE, SUM(GASTO_OPE) as VALOR FROM [dbriesgos].[dbo].GASTO_PROV_OPE_DIARIA WHERE FC_DIA = CONVERT(varchar,'''+ CAST(@FecRep AS VARCHAR(10)) +''',23)'
	+' 	
		UNION
		SELECT ''SGASPROVCONTA'' as VARIABLE, SUM(GASTO_OPE) as VALOR FROM [dbriesgos].[dbo].GASTO_PROV_OPE_DIARIA WHERE FC_DIA = CONVERT(varchar,'''+ CAST(@FecRep AS VARCHAR(10)) +''',23);
	'+'
		UPDATE DW_Raw_v2.dbo.CMGMora_Recaudo
		SET 
			SSTKPROV = @SSTKPROV
			,SGASPROVCART = @SGASPROVCART
			,SGASPROVCONTA = @SGASPROVCONTA 
		WHERE STIPCOD = 7 '
	+N'';

BEGIN TRY
    EXEC sp_executesql @SQL;
END TRY
BEGIN CATCH


	IF NOT EXISTS (SELECT 1 FROM [dbriesgos].[dbo].GASTO_PROV_OPE_DIARIA WHERE FC_DIA = @FecRep )
		BEGIN
			SELECT @NombreTabla as VARIABLE , 'NO EXISTE LA TABLA' as VALOR UNION
			SELECT 'SSTKPROV' as VARIABLE , '0.00' as VALOR UNION
			SELECT 'SGASPROVCART' as VARIABLE , '0.00' as VALOR UNION
			SELECT 'SGASPROVCONTA' as VARIABLE , '0.00' as VALOR 

			SET @SSTKPROV = 0.0;
			SET @SGASPROVCART = 0.0;
			SET @SGASPROVCONTA = 0.0;

			UPDATE DW_Raw_v2.dbo.CMGMora_Recaudo
			SET 
				SSTKPROV = @SSTKPROV
				,SGASPROVCART = @SGASPROVCART
				,SGASPROVCONTA = @SGASPROVCONTA 
			WHERE STIPCOD = 7 
		END
END CATCH


