USE [storage]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--INGRESAR FECHA
DECLARE @FecRep DATE = '2026-10-03'



IF OBJECT_ID('tempdb..#SECVAL') IS NOT NULL 
DROP TABLE #SECVAL;

SELECT SCODSEC INTO #SECVAL FROM storage.[com_act].SDAS001 WHERE SFECPRO= @FecRep
EXCEPT
SELECT RCODSEC FROM storage.ref.FJERCOR02(@FecRep)

CREATE CLUSTERED INDEX IX_Temp_Vendedor ON #SECVAL(SCODSEC);

;with cta_a as (
	SELECT 
		HSALCAPMN, HCODSEC, HSUCCLI, HASEOPER, HCTACLI, HDESCLI, HCODOPE, HCODMOD, HTIPOPE, HSUBTIP
	FROM storage.[com_act].HCDA001 WHERE HFECPRO = @FecRep
)
SELECT 
	'FC' NIVEL
	,A.HASEOPER Asesor_Operativo
	,A.HCTACLI Cuenta_Cliente
	,A.HDESCLI Nom_Cliente
	,A.HCODOPE Operacion
	,A.HSALCAPMN Saldo_Capital
	,_P3.RDESGRU02 as Grupo
	,ISNULL(C.RDESTER,'NULL') Territorio
	,C.RDESCOR Corredor
	,C.RDESAGE Agencia_Cli
	,B.RDESUNI Unidad_Negocio
FROM cta_a A
LEFT JOIN (select * from storage.ref.FJERCOR02(@FecRep)) B on A.HCODSEC = B.RCODSEC
LEFT JOIN storage.ref.vjercor03 C on A.HSUCCLI = C.RCODAGE
LEFT JOIN STORAGE.[COM_ACT].RETP002 _P2 ON A.HCODMOD=_P2.RCODMOD AND A.HTIPOPE=_P2.RTIPOPE AND _P2.RSUBTIP=A.HSUBTIP 
LEFT JOIN STORAGE.[COM_ACT].RETP001 _P1 ON A.HCODMOD=_P1.RCODMOD AND A.HTIPOPE=_P1.RTIPOPE 
LEFT JOIN STORAGE.[COM_ACT].RETP003 _P3 ON ISNULL(_P2.RCODPROD,_P1.RCODPROD)=_P3.RCODPROD 
WHERE A.HASEOPER IN ('','--') OR A.HASEOPER IS NULL 
OR EXISTS ( SELECT 1  FROM #SECVAL t1 WHERE t1.SCODSEC=A.HASEOPER)
ORDER BY C.RCODTER, C.RCODCOR, C.RDESAGE
DROP TABLE #SECVAL


--select DISTINCT RCODAGE,RDESAGE from storage.ref.vjercor04 where rdester='SUR 1.'
--select DISTINCT RCODAGE from storage.ref.vjercor03 where rdester='SUR 1'
 