USE storage
GO

DECLARE @FecRep date = GETDATE()
PRINT @FecRep

SELECT TOP 11 RFEC INTO #RFEC
FROM storage.ref.RCALEN001
WHERE RCIEBT = 1 AND RFEC < @FecRep 
ORDER BY RFEC DESC

SELECT SUM(SSRECUMN) SRECCAST12M
FROM storage.[com_act].[SDAS005]
WHERE SFECPRO IN (SELECT RFEC FROM #RFEC) AND SCODAGR = 1

DROP TABLE #RFEC	





